FROM debian:trixie-slim AS build

RUN apt-get update \
    && apt-get install --no-install-recommends -y bash ca-certificates cmake curl ninja-build xz-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . .

RUN cmake --preset static-release -DPID0_BUILD_TESTS=OFF
RUN cmake --build --preset static-release --target pid0-example

FROM scratch

COPY --from=build /src/build/static-release/example/pid0-example /pid0-example

ENTRYPOINT ["/pid0-example"]
