set(PID0_TARGET_ID x86_64-linux-gnu CACHE STRING "" FORCE)
include("${CMAKE_CURRENT_LIST_DIR}/cpkt-linux.cmake")
set(PID0_AFLPP_RESOLVER "${CMAKE_CURRENT_LIST_DIR}/../../scripts/cpkt-aflpp.sh")
execute_process(COMMAND bash "${PID0_AFLPP_RESOLVER}" discover
  RESULT_VARIABLE result OUTPUT_VARIABLE description ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Unable to provision pinned AFL++: ${error}")
endif()
foreach(key IN ITEMS cc cxx)
  string(REGEX MATCH "${key}=([^\r\n]+)" match "${description}")
  if(NOT match)
    message(FATAL_ERROR "AFL++ resolver did not report ${key}")
  endif()
  set(afl_${key} "${CMAKE_MATCH_1}")
endforeach()
set(CMAKE_C_COMPILER "${afl_cc}" CACHE FILEPATH "Pinned AFL++ C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${afl_cxx}" CACHE FILEPATH "Pinned AFL++ C++ compiler" FORCE)
